### PR TITLE
feat/unit_tests

### LINKED ISSUE #18: New Unit Tests
I removed the old tests because they were outdated and the setup was broken anyway.

There's one example test, but it's not really useful. We could stick with Jest, but it's worth poking around at other options too, like [Vitest](https://vitest.dev/), at @veritem's suggestion

### PR DESCRIPTION
**Pull request by veritem**
This pr aims to fix #18. I'm still new to this codebase, but @jonathandewitt-dev if you can pinpoint to me the most important parts of the codebase to be tested, I'll make sure to fix them asp. Vite intergration is done.

### CODE REVIEW

**Comment by jonathandewitt-dev** [comment]
Nice! I think the most important stuff to test will be the functionality exposed to the user. As a secondary concern, we should test things that concern us as developers just so we can push enhancements with more confidence.

In that first category, a couple things come to mind first. The entire config should be untouchable from outside. Meaning...
```ts
const config = { name: 'user', state: { firstName: 'Jon' } }
const state = createStore(config)
config.state.firstName = 'Verite' // this should not impact any part of the `state` object above
```
Similarly, getters should not be assignable.
```ts
const state = createStore({ name: 'user', state: { firstName: 'Jon' } })
state.getters.firstName = 'Verite' // this should result in an error preventing the assignment
```
These are the first things that come to mind, but we can keep an open discussion around what else to test

**Review by bcdewitt — CHANGES_REQUESTED** [review]
Believe me when I say this: you don't want to have two different lock files. I would either request to move the repo to use pnpm or align with the existing code and use npm.

**Comment by bcdewitt** [comment]
@veritem The public code is likely the best place to start for testing. From what I'm seeing, that would basically be the various ways of using the `createStore()` function.

**Comment by jonathandewitt-dev** [comment]
Quick note: the whitespace characters in the changed files are inconsistent with the rest of the project, and it looks like they're the only change in `tsconfig.json`. Can we remove all that/convert to 2-space indents?

This being said, I've heard spaces are suddenly an accessibility concern? lmao, so we can always switch to tabs in the [ESLint](https://github.com/Thunder-Solutions/Thunder-State/issues/23) issue, but that can be a separate task

**Comment by jonathandewitt-dev** [comment]
Woops, I didn't think that would close this PR, that's strange. I'll try to work this out for you.

**Comment by jonathandewitt-dev** [comment]
Sorry about the mixup, this draft PR can continue on #24

**Pull request closed without merging**
